title: Abby Taylor's Works
description: In this site you will find a portfolio including the personal projects, research projects, and educational projects from Abby Taylor.
baseurl: "/"
url: ""
theme: jekyll-theme-tactile

search_enabled: false
## aux links can be made for repo and other stuff
